In [1]:
import json
import pandas as pd
pd.set_option('display.max_columns', None)

with open('full_format_recipes.json', 'r') as f:
    data = json.load(f)
data_withsteps = pd.DataFrame(data)

# EDA
<p style="font-size:20px; color:#4CAF50; font-weight:bold;">Exploratory Data Analysis</p>

In [2]:
data_withsteps.head()

,directions,fat,date,categories,calories,desc,protein,rating,title,ingredients,sodium
0,"[1. Place the stock, lentils, celery, carrot, ...",7.0,2006-09-01T04:00:00.000Z,"[Sandwich, Bean, Fruit, Tomato, turkey, Vegeta...",426.0,None,30.0,2.500,"Lentil, Apple, and Turkey Wrap","[4 cups low-sodium vegetable or chicken stock,...",559.0
1,[Combine first 9 ingredients in heavy medium s...,23.0,2004-08-20T04:00:00.000Z,"[Food Processor, Onion, Pork, Bake, Bastille D...",403.0,This uses the same ingredients found in boudin...,18.0,4.375,Boudin Blanc Terrine with Red Onion Confit,"[1 1/2 cups whipping cream, 2 medium onions, c...",1439.0
2,[In a large heavy saucepan cook diced fennel a...,7.0,2004-08-20T04:00:00.000Z,"[Soup/Stew, Dairy, Potato, Vegetable, Fennel, ...",165.0,None,6.0,3.750,Potato and Fennel Soup Hodge,"[1 fennel bulb (sometimes called anise), stalk...",165.0
3,[Heat oil in heavy large skillet over medium-h...,NaN,2009-03-27T04:00:00.000Z,"[Fish, Olive, Tomato, Sauté, Low Fat, Low Cal,...",NaN,The Sicilian-style tomato sauce has tons of Me...,NaN,5.000,Mahi-Mahi in Tomato Olive Sauce,"[2 tablespoons extra-virgin olive oil, 1 cup c...",NaN
4,[Preheat oven to 350°F. Lightly grease 8x8x2-i...,32.0,2004-08-20T04:00:00.000Z,"[Cheese, Dairy, Pasta, Vegetable, Side, Bake, ...",547.0,None,20.0,3.125,Spinach Noodle Casserole,"[1 12-ounce package frozen spinach soufflé, th...",452.0

In [3]:
# data_withsteps.to_csv('full_format_recipes.csv')

In [4]:

data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20130 entries, 0 to 20129
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   directions   20111 non-null  object
 1   fat          15908 non-null  float64
 2   date         20111 non-null  object
 3   categories   20111 non-null  object
 4   calories     15976 non-null  float64
 5   desc         13495 non-null  object
 6   protein      15929 non-null  float64
 7   rating       20100 non-null  float64
 8   title        20111 non-null  object
 9   ingredients  20111 non-null  object
 10  sodium       15974 non-null  float64
dtypes: float64(5), object(6)
memory usage: 1.7+ MB

In [5]:
data_withsteps.describe()

                fat      calories        protein        rating        sodium
count  1.590800e+04  1.597600e+04   15929.000000  20100.000000  1.597400e+04
mean   3.460975e+02  6.307857e+03      99.946199      3.713060  6.211474e+03
std    2.043102e+04  3.585851e+05    3835.616663      1.343144  3.328903e+05
min    0.000000e+00  0.000000e+00       0.000000      0.000000  0.000000e+00
25%    7.000000e+00  1.980000e+02       3.000000      3.750000  8.000000e+01
50%    1.700000e+01  3.310000e+02       8.000000      4.375000  2.940000e+02
75%    3.300000e+01  5.860000e+02      27.000000      4.375000  7.110000e+02
max    1.722763e+06  3.011122e+07  236489.000000      5.000000  2.767511e+07

In [6]:
data_withsteps.sort_values(by='calories', ascending=False).head(10)['calories']

11444    30111218.0
6400     29997918.0
19749    13062948.0
2985      4518216.0
1308      4157357.0
9778      4157357.0
6945      3358273.0
5165      3358029.0
16276       54512.0
8232        24117.0
Name: calories, dtype: float64

In [7]:
data_withsteps.isnull().sum()

directions       19
fat            4222
date             19
categories       19
calories       4154
desc           6635
protein        4201
rating           30
title            19
ingredients      19
sodium         4156
dtype: int64

In [8]:
data_withsteps[data_withsteps['calories'] > 1500].count()

directions     597
fat            597
date           597
categories     597
calories       597
desc           425
protein        597
rating         597
title          597
ingredients    597
sodium         597
dtype: int64

In [9]:
data_withsteps.sort_values(by='sodium', ascending=False).head(10)

,directions,fat,date,categories,calories,desc,protein,rating,title,ingredients,sodium
11444,[Stir together all ingredients except pastry d...,1722763.0,2006-10-20T15:17:12.000Z,"[Berry, Fruit, Nut, Dessert, Bake, Christmas, ...",30111218.0,Don't be nervous about making meatless minceme...,200968.0,4.375,Pear-Cranberry Mincemeat Lattice Pie,"[2 firm-ripe Anjou pears, peeled, cored, and f...",27675110.0
6400,[Put a large baking sheet on oven rack in midd...,1716279.0,2006-07-20T20:48:24.000Z,"[Egg, Fruit, Bake, Blueberry, Summer, Tapioca,...",29997918.0,If you've never had pie made from wild blueber...,200210.0,4.375,Deep-Dish Wild Blueberry Pie,"[1 1/4 cups packed light brown sugar, 5 tables...",27570999.0
19749,[Position rack in center of oven and preheat t...,747374.0,2004-08-20T04:00:00.000Z,"[Berry, Fruit, Nut, Dessert, Bake, Thanksgivin...",13062948.0,None,87188.0,4.375,"Apricot, Cranberry and Walnut Pie","[1 cup (packed) golden brown sugar, 2 large eg...",12005810.0
2985,"[Soak bread in water to cover 30 minutes, then...",44198.0,2008-05-12T21:04:07.000Z,"[Food Processor, Backyard BBQ, Ground Lamb, Sp...",4518216.0,Köfte are a street-food favorite in the Middle...,166471.0,5.000,Lamb Köfte with Tarator Sauce,"[3 slices firm white sandwich bread, torn into...",7540990.0
6945,[Position rack in center of oven and preheat t...,186660.0,2004-08-20T04:00:00.000Z,"[Chocolate, Nut, Dessert, Bake, Christmas, Tha...",3358273.0,None,58334.0,3.125,Chocolate-Almond Pie,[4 ounces bittersweet (not unsweetened) or sem...,3449512.0
5165,[Position rack in center of oven and preheat t...,186642.0,2004-08-20T04:00:00.000Z,"[Fruit, Dessert, Bake, Christmas, Thanksgiving...",3358029.0,None,58324.0,3.125,Caramelized Apple and Pear Pie,"[1/2 cup applejack brandy or brandy, 1/2 cup d...",3449373.0
9778,[Wash rice in several changes of cold water in...,221495.0,2007-08-24T18:04:29.000Z,"[Lamb, Rice, Vegetable, Braise, Dinner, Raisin...",4157357.0,"This lamb-rich, Uzbek-style pilaf is typical o...",236489.0,5.000,"Rice Pilaf with Lamb, Carrots, and Raisins","[3 cups basmati rice (7 ounces), 1 medium onio...",3134853.0
1308,[Wash rice in several changes of cold water in...,221495.0,2007-08-24T18:04:29.000Z,"[Lamb, Rice, Vegetable, Braise, Dinner, Raisin...",4157357.0,"This lamb-rich, Uzbek-style pilaf is typical o...",236489.0,5.000,"Rice Pilaf with Lamb, Carrots, and Raisins","[3 cups basmati rice (7 ounces), 1 medium onio...",3134853.0
3285,[Preheat oven to 400°F. Stir salt and 5 egg wh...,20.0,2007-01-18T04:46:01.000Z,"[Salad, Egg, Fish, Olive, Bake, Roast, Bass, C...",417.0,Roasting the fish in salt makes it very moist ...,53.0,5.000,Whole Branzino Roasted in Salt,"[1 3-pound box coarse kosher salt, 5 (or more)...",132220.0
16258,"[Preheat oven to 400°F. Toss tomatoes, bell pe...",20.0,2004-08-20T04:00:00.000Z,"[Fish, Pepper, Tomato, Appetizer, Bake, Christ...",425.0,"The salt creates a seal around the fish, which...",49.0,4.375,Red Snapper Baked in Salt with Romesco Sauce,"[3 large plum tomatoes, 2 large red bell peppe...",132025.0

In [10]:
data_withsteps[data_withsteps['sodium'] > 1500].count()

directions     1375
fat            1374
date           1375
categories     1375
calories       1375
desc           1009
protein        1374
rating         1375
title          1375
ingredients    1375
sodium         1375
dtype: int64

In [11]:
data_withsteps[data_withsteps['calories'] < 50].count()

directions     585
fat            574
date           585
categories     585
calories       585
desc           405
protein        577
rating         585
title          585
ingredients    585
sodium         583
dtype: int64

In [12]:
data_withsteps[data_withsteps['calories'] < 50].head(10)

,directions,fat,date,categories,calories,desc,protein,rating,title,ingredients,sodium
27,[Preheat oven to 275°F. Mix sugar and spices i...,0.0,2007-07-26T17:36:37.000Z,"[Bake, Kid-Friendly, Pear, Spice, Healthy, Bon...",14.0,"Use a V-slicer (a simple, inexpensive version ...",0.0,2.500,Dried Pear Crisps,"[1 tablespoon sugar, 1/4 teaspoon ground ginge...",0.0
76,[In a large bowl whisk together the lime juice...,0.0,2004-08-20T04:00:00.000Z,"[Salad, Appetizer, Vegetarian, Quick & Easy, L...",26.0,None,1.0,3.125,South American-Style Jícama and Orange Salad,"[1/3 cup fresh lime juice, 1 1/2 teaspoons sal...",364.0
136,[Bring water to a boil with chicken wings in a...,1.0,2004-08-20T04:00:00.000Z,"[Soup/Stew, Chicken, Poultry, Winter, Chill, G...",23.0,None,2.0,0.000,Low-Fat Chicken Stock,"[10 cups water, 2 1/2 pounds chicken wings, 1 ...",54.0
168,"[Whisk together mayonnaise, egg, mustard, Old ...",3.0,2004-08-20T04:00:00.000Z,"[Ginger, Tomato, Appetizer, Bake, Cocktail Par...",46.0,None,3.0,4.375,Miniature Crab Cakes with Tomato Ginger Jam,"[1/2 cup mayonnaise, 1 large egg, 1 tablespoon...",119.0
285,"[When salting water for cooking, use 1 tablesp...",NaN,2004-08-20T04:00:00.000Z,"[Boil, Gourmet]",0.0,None,NaN,3.750,Salted Water for Boiling,"[Salt, Water]",0.0
292,[Bring all ingredients to a boil in an 8- to 1...,1.0,2004-08-20T04:00:00.000Z,"[Soup/Stew, Chicken, Vegetable, Simmer, Gourmet]",22.0,None,2.0,0.000,Chicken Stock,"[1 (3 1/2- to 4 1/2-pound) whole chicken, cut ...",75.0
320,[Cut tomatoes in half crosswise and seed if de...,0.0,2004-08-20T04:00:00.000Z,"[Condiment/Spread, Sauce, Onion, Tomato, Appet...",20.0,This salsa is used to flavor Frijoles Borracho...,1.0,4.375,Fresh Tomato Salsa,"[1/2 pound plum tomatoes, 2 fresh serrano chil...",483.0
361,[Put oven rack in middle position and preheat ...,0.0,2004-08-20T04:00:00.000Z,"[Bread, Condiment/Spread, Food Processor, Bake...",14.0,As a crisp topping for pasta or steamed vegeta...,1.0,5.000,Toasted Baguette Crumbs,"[1 (12-inch) piece day-old baguette, cut into ...",30.0
363,"[Preheat oven to 400°F., In a dry small heavy ...",1.0,2004-08-20T04:00:00.000Z,"[Bake, Cocktail Party, Low Cal, Spice, Gourmet]",21.0,This recipe can be prepared in 45 minutes or l...,0.0,3.750,Spiced Pita Toasts,"[4 teaspoons cumin seeds, 1 teaspoon coarse sa...",38.0
365,"[Cut up leek, carrot, and celery and in a larg...",0.0,2004-08-20T04:00:00.000Z,"[Sauce, Soup/Stew, Herb, Vegetable, Gourmet]",33.0,None,1.0,4.375,Court Bouillon,[1/2 small leek (white and pale green parts on...,624.0

In [13]:
duplicate_rows = data_withsteps.duplicated(subset=['title', 'calories', 'protein', 'fat', 'sodium'])
duplicate_count = duplicate_rows.sum()
duplicate_count

1902

# insights from EDA

- Dari hasil analisis data, terdapat banyak nilai kosong yang perlu dibersihkan.
- Terdapat nilai kalori yang sangat tinggi hingga lebih dari 30.000, yang tidak realistis untuk satu porsi makanan. Untuk memastikan data lebih representatif, kita perlu menetapkan batasan (threshold) yang realistis. Kalori yang wajar untuk makanan bisa dibatasi, misalnya, antara 1.000 hingga 1.500 kalori untuk makanan berkalori tinggi.

- Kandungan sodium juga menunjukkan banyak outlier, dengan beberapa nilai melebihi batas konsumsi harian yang direkomendasikan. Mengingat rata-rata sodium untuk makanan berada di kisaran 800-1.000 mg, kita bisa menetapkan ambang batas sekitar 1.500 mg untuk menjaga data tetap relevan.

- Terdapat sejumlah data duplikat dalam dataset, yang perlu dihapus untuk mencegah redundansi dan kesalahan dalam analisis. Mengidentifikasi duplikat berdasarkan atribut penting seperti judul, kalori, dan bahan akan membantu kita mempertahankan data yang unik.

- Awalnya, data dengan nilai kalori di bawah 50 tampak seperti outlier. Namun, setelah ditinjau lebih lanjut, ternyata data ini merujuk pada resep makanan pendamping seperti saus atau kaldu.

# Data Cleaning

In [14]:
data_withsteps.dropna(inplace=True)

In [15]:
data_withsteps.isnull().sum()

directions     0
fat            0
date           0
categories     0
calories       0
desc           0
protein        0
rating         0
title          0
ingredients    0
sodium         0
dtype: int64

In [16]:
data_withsteps.describe()

                fat      calories        protein        rating        sodium
count  1.060800e+04  1.060800e+04   10608.000000  10608.000000  1.060800e+04
mean   4.006124e+02  7.403782e+03     121.733503      3.804558  7.275736e+03
std    2.380737e+04  4.188648e+05    4553.387738      1.263118  3.886472e+05
min    0.000000e+00  0.000000e+00       0.000000      0.000000  0.000000e+00
25%    9.000000e+00  2.060000e+02       3.000000      3.750000  1.000000e+02
50%    1.900000e+01  3.510000e+02       9.000000      4.375000  3.270000e+02
75%    3.500000e+01  6.120000e+02      29.000000      4.375000  7.652500e+02
max    1.722763e+06  3.011122e+07  236489.000000      5.000000  2.767511e+07

In [17]:
data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10608 entries, 1 to 20129
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   directions   10608 non-null  object
 1   fat          10608 non-null  float64
 2   date         10608 non-null  object
 3   categories   10608 non-null  object
 4   calories     10608 non-null  float64
 5   desc         10608 non-null  object
 6   protein      10608 non-null  float64
 7   rating       10608 non-null  float64
 8   title        10608 non-null  object
 9   ingredients  10608 non-null  object
 10  sodium       10608 non-null  float64
dtypes: float64(5), object(6)
memory usage: 994.5+ KB

In [18]:
data_withsteps.drop_duplicates(subset=['title', 'calories', 'protein', 'fat', 'sodium'], inplace=True)

In [19]:
data_withsteps.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9580 entries, 1 to 20129
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   directions   9580 non-null   object
 1   fat          9580 non-null   float64
 2   date         9580 non-null   object
 3   categories   9580 non-null   object
 4   calories     9580 non-null   float64
 5   desc         9580 non-null   object
 6   protein      9580 non-null   float64
 7   rating       9580 non-null   float64
 8   title        9580 non-null   object
 9   ingredients  9580 non-null   object
 10  sodium       9580 non-null   float64
dtypes: float64(5), object(6)
memory usage: 898.1+ KB

In [20]:
data_withsteps.describe()

                fat      calories        protein       rating        sodium
count  9.580000e+03  9.580000e+03    9580.000000  9580.000000  9.580000e+03
mean   4.178757e+02  7.718117e+03     108.373173     3.809825  7.668347e+03
std    2.494991e+04  4.387175e+05    4138.149307     1.247309  4.077134e+05
min    0.000000e+00  0.000000e+00       0.000000     0.000000  0.000000e+00
25%    9.000000e+00  2.140000e+02       4.000000     3.750000  1.097500e+02
50%    1.900000e+01  3.670000e+02      10.000000     4.375000  3.390000e+02
75%    3.600000e+01  6.270000e+02      31.000000     4.375000  7.900000e+02
max    1.722763e+06  3.011122e+07  236489.000000     5.000000  2.767511e+07

In [21]:
data_withsteps = data_withsteps[data_withsteps['calories'] < 1500]

In [22]:
data_withsteps.describe()

               fat     calories      protein       rating         sodium
count  9190.000000  9190.000000  9190.000000  9190.000000    9190.000000
mean     24.072470   429.277693    18.946246     3.807399     686.768118
std      21.519717   299.494039    23.514315     1.246569    3193.214406
min       0.000000     0.000000     0.000000     0.000000       0.000000
25%       9.000000   209.000000     4.000000     3.750000     103.000000
50%      18.000000   351.000000     9.000000     4.375000     317.000000
75%      33.000000   587.000000    28.000000     4.375000     719.000000
max     140.000000  1497.000000   234.000000     5.000000  132220.000000

In [23]:
data_withsteps = data_withsteps[data_withsteps['sodium'] < 1500]

In [24]:
data_withsteps.describe()

               fat     calories      protein       rating       sodium
count  8475.000000  8475.000000  8475.000000  8475.000000  8475.000000
mean     22.937227   406.026077    16.577345     3.804351   390.673628
std      20.568486   280.094473    20.407774     1.242953   370.477634
min       0.000000     0.000000     0.000000     0.000000     0.000000
25%       9.000000   204.000000     3.000000     3.750000    90.000000
50%      18.000000   332.000000     8.000000     4.375000   272.000000
75%      31.000000   548.500000    23.000000     4.375000   597.000000
max     135.000000  1497.000000   203.000000     5.000000  1499.000000

In [ ]:
data_withsteps['total_steps'] = data_withsteps['directions'].apply(
    lambda x: len(x) if isinstance(x, list) else len(eval(x)) if isinstance(x, str) and x.startswith('[') else 0
)

data_withsteps['total_ingredients'] = data_withsteps['ingredients'].apply(
    lambda x: len(x) if isinstance(x, list) else len(eval(x)) if isinstance(x, str) and x.startswith('[') else 0
)
data_withsteps.head()

,directions,fat,date,categories,calories,desc,protein,rating,title,ingredients,sodium,total_steps,total_ingredients
1,[Combine first 9 ingredients in heavy medium s...,23.0,2004-08-20T04:00:00.000Z,"[Food Processor, Onion, Pork, Bake, Bastille D...",403.0,This uses the same ingredients found in boudin...,18.0,4.375,Boudin Blanc Terrine with Red Onion Confit,"[1 1/2 cups whipping cream, 2 medium onions, c...",1439.0,5,28
5,"[Mix basil, mayonnaise and butter in processor...",79.0,2004-08-20T04:00:00.000Z,"[Sandwich, Food Processor, Tomato, Kid-Friendl...",948.0,This recipe can be prepared in 45 minutes or l...,19.0,4.375,The Best Blts,[2 1/2 cups (lightly packed) fresh basil leave...,1042.0,3,9
8,"[Stir together soy sauce, sugar, sesame oil, w...",10.0,2004-08-20T04:00:00.000Z,"[Beef, Ginger, Sauté, Stir-Fry, Quick & Easy, ...",170.0,Bulgogi,7.0,4.375,Korean Marinated Beef,"[1/4 cup soy sauce, 1 tablespoon sugar, 2 teas...",1272.0,3,10
10,[Heat oil in heavy large skillet over medium-h...,5.0,2004-08-20T04:00:00.000Z,"[Milk/Cream, Dairy, Side, Thanksgiving, Rosema...",256.0,Simmering the yams fills them with flavor and ...,4.0,3.750,"Yams Braised with Cream, Rosemary and Nutmeg","[4 teaspoons olive oil, 1/2 cup finely chopped...",30.0,1,7
12,[Preheat oven to 350°F. Coat cake pans with no...,48.0,2012-09-18T04:00:00.000Z,"[Cake, Chocolate, Fruit, Dessert, Bake, Kid-Fr...",766.0,"This cake is perfect for beginners—it's moist,...",12.0,4.375,Banana-Chocolate Chip Cake With Peanut Butter ...,"[Nonstick vegetable oil spray, 3 cups all-purp...",439.0,5,18

In [29]:
data_withsteps.to_csv('full_format_recipes.csv')